version: '3'
services:
  db:
    image: postgres
  redis:
    image: 'redis:alpine'
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/testapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis