default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

docker: &docker
  host: db
  username: postgres
  password:

development:
  <<: *default
  <<: *docker
  database: testapp_dev


test:
  <<: *default
  <<: *docker
  database: testapp_test